default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: karban_board
  password: karban2434
  host: localhost

development:
  <<: *default
  database: karban_time_travel

test:
  <<: *default
  database: karban_time_travel_test

production:
  primary: &primary_production
    <<: *default
    database: karban_time_travel_production
    username: karban_board
    password: <%= ENV["KANBAN_TIME_TRAVEL_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: karban_time_travel_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: karban_time_travel_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: karban_time_travel_production_cable
    migrations_paths: db/cable_migrate